import networkx as nx
import pandas as pd



def build_variable_dependency_graph():
    G = nx.Graph()
    common_columns = ['CASEID','CASENO','CASENUMBER','CATEGORY','PSU','VEHNO','OCCNO']


    G.add_node('CRASH',type='table',description="The CRASH table is the base table for all other CISS tables. It contains one row per case and contains basic crash level information. ")
    G.add_node('GV',type='table',description="The GV table contains basic information regarding the vehicle and will contain one row for each motor vehicle in the crash that sustained a harmful event.")
    G.add_node('EVENT',type='table',description="The EVENT table contains one row for each harmful event in the crash.")
    G.add_node('OCC',type='table',description="The OCC table contains information regarding all the occupants of in-transport towed CISS-applicable vehicles.")
    G.add_node('OCCONTACT',type='table',description="The OCCONTACT table contains information regarding occupant contacts documented by the crash technician during the vehicle inspection.")
    G.add_node('AVOID',type='table',description="The AVOID table reports the vehicle's crash avoidance features that may be installed in the vehicle.")
    G.add_node('VPICDECODE',type='table',description="The VPICDECODE table reports various data derived from the vehicle's VIN. A row will be present for all vehicles with a model year of 1981 and forward and having a known VIN that passes the check digit routine without error.")


    G.add_node('CASEID',type='common column',description='Case ID is a unique number generated by the CISS data entry application. A case can be uniquely identified across ALL data years using this number.')
    G.add_node('CASENO',type='common column',description='SEQUENTIAL CASE NUMBER is a 1 to 3 digit number that uniquely identifies a case within a PSU and Crash Year.')
    G.add_node('CASENUMBER',type='common column',description='CASE NUMBER is assigned by the system at case creation and cannot be changed. It is unique among all NHTSA crash investigation-based programs. The variable is a combination of the Study ID (the Study ID for CISS is 1), PSU, Crash Year, Sequential Case Number (CASENO), and Category separated by hyphens.')
    G.add_node('CATEGORY',type='common column',description='The Category identifies which CISS sampling domain the case is classified based upon the initial police crash report review and listing by the CISS technician or the automated stratification algorithm. This is not a linking variable; however, it is present in all the datasets.')
    G.add_node('PSU',type='common column',description='Primary Sampling Unit (PSU) refers to the sampling units in the first stage of the multi-stage sampling. In the CISS, PSU is a county or group of counties. Selected PSUs are data collection sites where crashes are sampled and investigated.')
    G.add_node('OCCNO',type='common column',description='Occupant numbers are assigned in a vehicle consecutively beginning with “1” and normally follow the numbering found on the police crash report. Only occupants of in-transport, towed, CISS-applicable (BODYTYPE 1-49) are captured in the data.')
    G.add_node('VEHNO',type='common column',description='Vehicle numbers are consecutive beginning with “1,” and normally follow the numbering found on the police crash report. All motor vehicles in the case/crash that sustain a harmful event are assigned a vehicle number regardless of whether the motor vehicle was or was not in-transport.')


    colums_df = pd.read_excel('Data/CISS/DataBaseInfo/CISS_schema.xlsx')
    for id,row in colums_df.iterrows():
        if row['column_name'] in common_columns:
            if row['key_identifier'] == 0:
                G.add_edge(row['column_name'],row['sheet_name'],property='is_column_of')
                # G.add_edge(row['sheet_name'],row['column_name'],property='has_column')
            if row['key_identifier'] == 1:
                G.add_edge(row['column_name'],row['sheet_name'],property='is_key_identifier_of')
                # G.add_edge(row['sheet_name'],row['column_name'],property='has_key_identifier')
        else:
            G.add_node(
                row['column_name'],
                type ='column',
                table =  row['sheet_name'],
                key_identifier = row['key_identifier'],
                description = row['description']
            )
            if row['key_identifier'] == 0:
                G.add_edge(row['column_name'],row['sheet_name'],property='is_column_of')
            if row['key_identifier'] == 1:
                G.add_edge(row['column_name'],row['sheet_name'],property='is_key_identifier_of')
    return G
